### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by gamefiend** [commitmas/pybluedot#4]
Are we planning to write tests for the utility?  If we are, I'd like to volunteer to write at least a few, because I'd like more experience writing tests.

**Comment by rnelson0** [comment]
I'm not sure if there's a defined plan per se (@Mierdin?) , but tests will absolutely be accepted!

**Comment by Mierdin** [comment]
Yes indeed, integration and unit tests are definitely part of this. I have a plan to push a common framework for running tests and linting checks, I just haven't had a chance to yet due to some personal stuff. So stay tuned for that
