### ISSUE TITLE
CLI command/subcommand structure.

### ISSUE THREAD

**Issue by gamefiend** [commitmas/pybluedot#6]
I want to start with writing the structure for the command/subcommand for pybluedot.

My basic approach would be to make a json/dict that holds the basic information for each command/subcommand in it.  It would look like:

```
subcommands = [
       search : {  
             name: "search",
             help: "Search the Nasa database",
             type: "string",
             options = [ 
                               {
                                 name: "--search-type",
                                 action: "store_const",
                                },
                                {
                                 name: "--limit-output",
                                 action: "store_const",
                                }
                              ] 
             function: "search_api"
        },
```

this object is then used to create the argparse object in a file called cli.py. I could define it strictly through argparse directly, but I think abstracting it into this structure will allow authors to add the pertinent information about their command more easily.  

I think the most important part of doing it this way is documenting the format and process for using it, which I am more than willing to do.  

What do we think about this approach?  Can I move forward with it, or would we like to do something else?

**Comment by jeorryb** [comment]
Sounds good to me!
